/**
 * 
 */
package dictionary.exceptions;

/**
 * An Exception to be thrown when a MagicalBag is empty.
 * 
 * @author S H S Wong
 * @version 03-10-2020
 */
public class EmptyMagicalBagException extends RuntimeException {

	/**
	 * A serial version unique ID generated by Eclipse for this class.
	 */
	private static final long serialVersionUID = -1272408305568986822L;
	
	/**
	 * Constructor
	 */
	public EmptyMagicalBagException() {
		super("The magical bag is empty!");
	}
}
