/**
 * 
 */
package dictionary.exceptions;

/**
 * An Exception to be thrown when a MagicalBag is full.
 * 
 * @author S H S Wong
 * @version 03-10-2020
 */
public class FullMagicalBagException extends RuntimeException {

	/**
	 * A serial version unique ID generated by Eclipse for this class.
	 */
	private static final long serialVersionUID = 959173510305905895L;

	/**
	 * Constructor
	 */
	public FullMagicalBagException() {
		super("The magical bag is full! No more items can be added.");
	}
}
