/**
 * 
 */
package dictionary.exceptions;

/**
 * This exception is thrown when a specified type of bag collection 
 * 	is not defined in this project.
 * 
 * @author S H S Wong
 * @version 03-10-2020
 */
public class UnsupportedMagicalBagTypeException extends RuntimeException {

	/**
	 * A serial version unique ID generated by Eclipse for this class.
	 */
	private static final long serialVersionUID = 4148016471349374212L;
	
	/**
	 * Constructor
	 */
	public UnsupportedMagicalBagTypeException() {
		super("Unsupported MagicalBag Type.");
	}
	
}
